version: '3'

services:
  arangodb:
    image: arangodb
    container_name: arangodb-tg
    volumes:
      - ./data:/var/lib/arangodb3
      - ./data-apps:/var/lib/arangodb3-apps
      - ./data-other:/data-other
    ports:
      - "8529:8529"
    environment:
      - ARANGO_NO_AUTH=1